open! Vocab

let kill_switch = ref false

open struct
  let one_ether = Z.(pow (of_int 10) 18)
end

let input = ref ""
let main_contract = ref ""
let intermediate_language = ref false
let cfg = ref false
let verify_timeout = ref 300
let z3timeout = ref 10000
let solc_ver : Solc.Ver.t option ref = ref None
let get_solc_ver () = Option.get !solc_ver
let use_manual_gc = ref true
let debug = ref ""
let inline_depth = ref (-1)
let alarm_filter = ref false
let uninterp_nonlinear = ref false (* experimental *)
let pow = ref false
let verbose = ref 1
let mk_report = ref false
let mode = ref Enums.Mode.Verify
let intra = ref false
let bit = ref 0
let inline_enforce = ref false

(** {b Note} We do not measure usage of SMT solvers' memory usage, as it is hard to control *)
let max_ocaml_memory_allowed_in_mb = ref (3 * 1024)

let struct_bit_usage = ref 512

(** Experimental, path generation setting, this is an enum-like argument *)
let pathgen = ref 1

module Chk = struct
  let io = ref false
  let dz = ref false
  let assert_ = ref false
  let el = ref false
  let su = ref false
  let erc20 = ref false
  let re = ref false
  let tx = ref false
  let reg = ref false
end

let kind_setter (kind : string) =
  let kind' = String.lowercase_ascii kind in
  match kind' with
  | "all" ->
    (* set all but reg checking *)
    Chk.io := true;
    Chk.dz := true;
    Chk.assert_ := true;
    Chk.el := true;
    Chk.su := false;
    Chk.erc20 := true;
    Chk.re := false
  | "io" -> Chk.io := true
  | "dz" -> Chk.dz := true
  | "as" | "assert" -> Chk.assert_ := true
  | "el" | "leak" -> Chk.el := true
  | "su" | "ka" | "kill" -> Chk.su := true
  | "re" -> Chk.re := true
  | "tx" -> Chk.tx := true
  | "erc20" -> Chk.erc20 := true
  | "reg" -> Chk.reg := true
  | _ -> invalid_arg ("invalid option in specifying bug types: " ^ kind)
;;

let re_safety_enforce = ref false

(** Exploit Configuration. *)
module E = struct
  (** Name of the [balance] variable in the contract. Automatically reasoned by heuristics. *)
  let balance_name = ref ""

  (** Name of the [allowance] variable in the contract. Automatically reasoned by heuristics. *)
  let allow_name = ref ""

  (** Name of the [totalSupply] variable in the contract. Automatically reasoned by heuristics. *)
  let total_name = ref ""

  (** reference report generated by a verifier *)
  let vrep : string option ref = ref None

  (** exploit, random search 1 *)
  let rand = ref false

  (** exploit, change-aware search *)
  let chase = ref false

  (** directory of language model. *)
  let lm_path = ref ""

  (** perform pruning powered by SmarTrim *)
  let pruning = ref true

  (** search strategy *)
  let search_strategy = ref Enums.Search_strategy.Increasing_order

  (** Maximum transaction depth other than the initial transaction (i.e. constructor call). *)
  let transaction_depth = ref 1000000000000000

  let skip_external_call = ref false

  (** How many queries will be disproven?

      Used for testing. if this is [Some n] and the final number of disproven queries is [n], then
      the program exits with code [0], else the program exits with code [88]. *)
  let expectation : int option ref = ref None

  let sslearn = ref false
  let preproof = ref false
  let exclude_unf = ref false

  (** how many vcs can be memoized on the memory; not developed yet *)
  let vc_memo = ref 0
end

(** Exploit time budget *)
let exploit_timeout = ref 1800

(** Maximum external call depth. (Currently Not Implemented) *)
let extern_depth = ref 1

let validate = ref false
let refined_vcgen = ref true
let init_eth = ref Z.(one_ether * of_int 100)
let send_eth = ref Z.(one_ether * of_int 100000)

module R = struct
  let tool_timeout = ref 180
  let loop_timeout = ref 1800
  let no_learn = ref false
  let no_diff = ref false
  let ksrc = ref ""
  let overify = ref false
  let pverify = ref false
  let compdir = ref ""
  let report = ref ""
end

module B = struct
  let seed_limit = ref (-1)

  (** change-unaware validation mode *)
  let no_chase = ref false

  let seed = ref ""
  let mutant = ref ""
  let ncores = ref 6
end

let outdir = ref ""
let split_payable = ref false

(** candidates of vulnerability lines *)
let candidates : string ref = ref ""

let activate_default_detector_if_unspecified () =
  let b = Chk.(!io || !dz || !assert_ || !el || !su || !erc20 || !re || !tx || !reg) in
  if not b then begin
    let open Chk in
    io := true;
    dz := true;
    el := true;
    su := true
  end;
  if !R.overify || !R.pverify then Chk.reg := true
;;

let print_detector_activation_status () =
  let open Chk in
  if !verbose > 0 then begin
    if !io then print_endline "[CHECKER] Integer Over/Underflows";
    if !dz then print_endline "[CHECKER] Division by Zero";
    if !assert_ then print_endline "[CHECKER] Assertion Violation";
    if !el then print_endline "[CHECKER] Ether Leak";
    if !su then print_endline "[CHECKER] Suicidal";
    if !erc20 then print_endline "[CHECKER] ERC20 Violation";
    if !re then print_endline "[CHECKER] Reentrancy";
    if !tx then print_endline "[CHECKER] Improper use of tx.origin";
    print_endline ""
  end
;;

(** Outdated and not used in this branch anymore *)
let basic_options =
  Arg.align ~limit:30
    [
      ("-inline_depth", Arg.Int (fun n -> inline_depth := n), "N the number of times being inlined");
      ("-alarm_filter", Arg.Set alarm_filter, " apply alarm filtering heuristic");
      ( "-uninterp_nonlinear",
        Arg.Set uninterp_nonlinear,
        " [experimental] use uninterpreted functions for nonlinear exps" );
      ( "-pow",
        Arg.Set pow,
        " when IO checker is on, verify power ops (true) or not (false) (default: false)" );
      ("-intra", Arg.Set intra, " verify intra-transactionally");
      ( "-bit",
        Arg.Int (fun n -> bit := n),
        "BIT restrict the number of bits for 256-bit expressions" );
      ("-inline_enforce", Arg.Set inline_enforce, " enforce inlining, without inlining heuristics");
      ("-path", Arg.Int (fun n -> pathgen := n), "N path enumeration mode - experimental");
      ( "-re_safety_enforce",
        Arg.Set re_safety_enforce,
        " perform reentrancy safety verification even when CEI pattern is obeyed." );
      (* exploit generation mode *)
      ("-edepth", Arg.Int (fun n -> extern_depth := n), "N maximum external function call depth");
      ( "-exploit_vrep",
        Arg.String (fun s -> E.vrep := Some s),
        "PATH reference report produced by a verifier" );
      ("-exploit_rand", Arg.Set E.rand, " explore transaction sequences in randomized order");
      ("-exploit_chase", Arg.Set E.chase, " change-aware symbolic execution");
      ( "-exploit_skip_external_call",
        Arg.Set E.skip_external_call,
        " skip external function calls; assume they do not change states" );
      ("-bug_seed", Arg.String (fun s -> B.seed := s), "PATH directory of seed contracts");
      ("-bug_mutant", Arg.String (fun s -> B.mutant := s), "PATH directory of mutant contracts");
      ( "-bug_seed_limit",
        Arg.Int
          (fun n ->
            assert (n > 0);
            B.seed_limit := n),
        "N maximum seed number. (default: unlimited)" );
      ( "-bug_no_chase",
        Arg.Set B.no_chase,
        " validate bug-existence using change-unaware symbolic execution" );
      ( "-ncores",
        Arg.Int
          (fun n ->
            assert (n > 0);
            B.ncores := n),
        "JOBS # of cores for lwt (default: 6)" );
    ]
;;

let options = ref basic_options
