(** reports for all basefiles. *)

(** Template type for final report. The final reports will be defined in {!Reports.Final}.

    {b Example} report for exploit mode is [(Exploit_r.Summary.t, Exploit_r.Tseq_c.t) t]. *)
type ('summary, 'result) t = {
  filename : string;
  basename : string;
  cpu_time : string;
  real_time : string;
  datetime : string;
  err_msg : string option;
  compiler_version : string;
  summary : 'summary option;
  result : 'result list option;
  log : string list;
}
[@@deriving show { with_path = false }, make, yojson] [@@yojson.allow_extra_fields]

(** Useful when ['summary] or ['result] is unit type. *)
let unit_to_yojson = [%yojson_of: unit]

(** Useful when ['summary] or ['result] is unit type. *)
let unit_of_yojson = [%of_yojson: unit]

module Loc = struct
  (** Location type generated by solidity compiler. Does very similar work to {!Lang.loc}. *)
  type t = { line : int; finish_line : int; offset : int; len : int }
  [@@deriving show { with_path = false }, make, yojson]
end
